// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v4.25.3
// source: proto/task.proto

package test_project

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ID            int64                  `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	ExpressionId  int64                  `protobuf:"varint,2,opt,name=ExpressionId,proto3" json:"ExpressionId,omitempty"`
	UserID        int64                  `protobuf:"varint,3,opt,name=UserID,proto3" json:"UserID,omitempty"`
	Arg1          float64                `protobuf:"fixed64,4,opt,name=Arg1,proto3" json:"Arg1,omitempty"`
	Arg2          float64                `protobuf:"fixed64,5,opt,name=Arg2,proto3" json:"Arg2,omitempty"`
	Operation     string                 `protobuf:"bytes,6,opt,name=Operation,proto3" json:"Operation,omitempty"`
	OperationTime int32                  `protobuf:"varint,7,opt,name=OperationTime,proto3" json:"OperationTime,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskRequest) Reset() {
	*x = TaskRequest{}
	mi := &file_proto_task_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskRequest) ProtoMessage() {}

func (x *TaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_task_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskRequest.ProtoReflect.Descriptor instead.
func (*TaskRequest) Descriptor() ([]byte, []int) {
	return file_proto_task_proto_rawDescGZIP(), []int{0}
}

func (x *TaskRequest) GetID() int64 {
	if x != nil {
		return x.ID
	}
	return 0
}

func (x *TaskRequest) GetExpressionId() int64 {
	if x != nil {
		return x.ExpressionId
	}
	return 0
}

func (x *TaskRequest) GetUserID() int64 {
	if x != nil {
		return x.UserID
	}
	return 0
}

func (x *TaskRequest) GetArg1() float64 {
	if x != nil {
		return x.Arg1
	}
	return 0
}

func (x *TaskRequest) GetArg2() float64 {
	if x != nil {
		return x.Arg2
	}
	return 0
}

func (x *TaskRequest) GetOperation() string {
	if x != nil {
		return x.Operation
	}
	return ""
}

func (x *TaskRequest) GetOperationTime() int32 {
	if x != nil {
		return x.OperationTime
	}
	return 0
}

type TaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ID            int64                  `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	ExpressionId  int64                  `protobuf:"varint,2,opt,name=ExpressionId,proto3" json:"ExpressionId,omitempty"`
	UserID        int64                  `protobuf:"varint,3,opt,name=UserID,proto3" json:"UserID,omitempty"`
	Error         bool                   `protobuf:"varint,4,opt,name=Error,proto3" json:"Error,omitempty"`
	Res           float64                `protobuf:"fixed64,5,opt,name=Res,proto3" json:"Res,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskResponse) Reset() {
	*x = TaskResponse{}
	mi := &file_proto_task_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskResponse) ProtoMessage() {}

func (x *TaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_task_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskResponse.ProtoReflect.Descriptor instead.
func (*TaskResponse) Descriptor() ([]byte, []int) {
	return file_proto_task_proto_rawDescGZIP(), []int{1}
}

func (x *TaskResponse) GetID() int64 {
	if x != nil {
		return x.ID
	}
	return 0
}

func (x *TaskResponse) GetExpressionId() int64 {
	if x != nil {
		return x.ExpressionId
	}
	return 0
}

func (x *TaskResponse) GetUserID() int64 {
	if x != nil {
		return x.UserID
	}
	return 0
}

func (x *TaskResponse) GetError() bool {
	if x != nil {
		return x.Error
	}
	return false
}

func (x *TaskResponse) GetRes() float64 {
	if x != nil {
		return x.Res
	}
	return 0
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_proto_task_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_proto_task_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_proto_task_proto_rawDescGZIP(), []int{2}
}

var File_proto_task_proto protoreflect.FileDescriptor

const file_proto_task_proto_rawDesc = "" +
	"\n" +
	"\x10proto/task.proto\x12\x04task\"\xc5\x01\n" +
	"\vTaskRequest\x12\x0e\n" +
	"\x02ID\x18\x01 \x01(\x03R\x02ID\x12\"\n" +
	"\fExpressionId\x18\x02 \x01(\x03R\fExpressionId\x12\x16\n" +
	"\x06UserID\x18\x03 \x01(\x03R\x06UserID\x12\x12\n" +
	"\x04Arg1\x18\x04 \x01(\x01R\x04Arg1\x12\x12\n" +
	"\x04Arg2\x18\x05 \x01(\x01R\x04Arg2\x12\x1c\n" +
	"\tOperation\x18\x06 \x01(\tR\tOperation\x12$\n" +
	"\rOperationTime\x18\a \x01(\x05R\rOperationTime\"\x82\x01\n" +
	"\fTaskResponse\x12\x0e\n" +
	"\x02ID\x18\x01 \x01(\x03R\x02ID\x12\"\n" +
	"\fExpressionId\x18\x02 \x01(\x03R\fExpressionId\x12\x16\n" +
	"\x06UserID\x18\x03 \x01(\x03R\x06UserID\x12\x14\n" +
	"\x05Error\x18\x04 \x01(\bR\x05Error\x12\x10\n" +
	"\x03Res\x18\x05 \x01(\x01R\x03Res\"\a\n" +
	"\x05Empty2k\n" +
	"\fOrchestrator\x12.\n" +
	"\tSetResult\x12\x12.task.TaskResponse\x1a\v.task.Empty\"\x00\x12+\n" +
	"\aGetTask\x12\v.task.Empty\x1a\x11.task.TaskRequest\"\x00B\x10Z\x0e./test_projectb\x06proto3"

var (
	file_proto_task_proto_rawDescOnce sync.Once
	file_proto_task_proto_rawDescData []byte
)

func file_proto_task_proto_rawDescGZIP() []byte {
	file_proto_task_proto_rawDescOnce.Do(func() {
		file_proto_task_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_task_proto_rawDesc), len(file_proto_task_proto_rawDesc)))
	})
	return file_proto_task_proto_rawDescData
}

var file_proto_task_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_task_proto_goTypes = []any{
	(*TaskRequest)(nil),  // 0: task.TaskRequest
	(*TaskResponse)(nil), // 1: task.TaskResponse
	(*Empty)(nil),        // 2: task.Empty
}
var file_proto_task_proto_depIdxs = []int32{
	1, // 0: task.Orchestrator.SetResult:input_type -> task.TaskResponse
	2, // 1: task.Orchestrator.GetTask:input_type -> task.Empty
	2, // 2: task.Orchestrator.SetResult:output_type -> task.Empty
	0, // 3: task.Orchestrator.GetTask:output_type -> task.TaskRequest
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_task_proto_init() }
func file_proto_task_proto_init() {
	if File_proto_task_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_task_proto_rawDesc), len(file_proto_task_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_task_proto_goTypes,
		DependencyIndexes: file_proto_task_proto_depIdxs,
		MessageInfos:      file_proto_task_proto_msgTypes,
	}.Build()
	File_proto_task_proto = out.File
	file_proto_task_proto_goTypes = nil
	file_proto_task_proto_depIdxs = nil
}
